"""Static catalogues: moods, context tags, resources, small steps, consents,
metric labels and the Story composition x trend matrix. Never LLM-generated."""

# Mood catalogue (all emotions valid — grouped, NOT good/bad colour coded)
# value: higher = feeling better; used only for internal statistics
MOODS = [
    {"key": "heavy",      "emoji": "😔", "cp": "1f614", "group": "low",     "value": 1, "en": "Heavy",      "hi": "भारी"},
    {"key": "anxious",    "emoji": "😰", "cp": "1f630", "group": "low",     "value": 2, "en": "Anxious",    "hi": "घबराहट"},
    {"key": "frustrated", "emoji": "😤", "cp": "1f624", "group": "low",     "value": 2, "en": "Frustrated", "hi": "खीझ"},
    {"key": "numb",       "emoji": "😶", "cp": "1f636", "group": "neutral", "value": 3, "en": "Numb",       "hi": "सुन्न"},
    {"key": "foggy",      "emoji": "😑", "cp": "1f611", "group": "neutral", "value": 3, "en": "Foggy",      "hi": "धुंधला"},
    {"key": "okay",       "emoji": "😐", "cp": "1f610", "group": "neutral", "value": 4, "en": "Okay",       "hi": "ठीक-ठाक"},
    {"key": "hopeful",    "emoji": "🌱", "cp": "1f331", "group": "bright",  "value": 5, "en": "Hopeful",    "hi": "उम्मीद"},
    {"key": "calm",       "emoji": "😌", "cp": "1f60c", "group": "bright",  "value": 5, "en": "Calm",        "hi": "शांत"},
    {"key": "energised",  "emoji": "⚡", "cp": "26a1",  "group": "bright",  "value": 6, "en": "Energised",  "hi": "ऊर्जा"},
]
MOOD_BY_KEY = {m['key']: m for m in MOODS}

CONTEXT_TAGS = ["work", "family", "relationships", "health", "sleep",
                "money", "exercise", "social", "travel", "weather", "other"]

# Wellbeing resource catalogue — locked by default, unlocked per-user by an
# admin/psychologist. Keys MUST match the frontend resources.tsx keys.
RESOURCE_CATALOG = [
    {"key": "breathing", "en": "A 2-minute breathing reset"},
    {"key": "sleep",     "en": "Winding down for better sleep"},
    {"key": "grounding", "en": "Grounding when things feel heavy"},
    {"key": "lowday",    "en": "Moving through a low day"},
    {"key": "seekhelp",  "en": "When to reach out for support"},
]
RESOURCE_KEYS = [r["key"] for r in RESOURCE_CATALOG]

# Curated One Small Step actions (never generated by an LLM)
SMALL_STEPS = [
    {"key": "breathing", "icon": "wind",    "en": "2-minute breathing", "hi": "2-मिनट की साँस",
     "en_desc": "Slow, even breaths to settle your body.", "hi_desc": "शरीर को शांत करने के लिए धीमी साँसें।"},
    {"key": "walk", "icon": "navigation", "en": "Short walk", "hi": "थोड़ी सैर",
     "en_desc": "A few minutes of gentle movement.", "hi_desc": "कुछ मिनट की हल्की गतिविधि।"},
    {"key": "stretch", "icon": "activity", "en": "Stretch", "hi": "स्ट्रेच",
     "en_desc": "Loosen up your shoulders and neck.", "hi_desc": "कंधों और गर्दन को ढीला करें।"},
    {"key": "hydrate", "icon": "droplet", "en": "Hydrate", "hi": "पानी पिएँ",
     "en_desc": "Have a glass of water.", "hi_desc": "एक गिलास पानी पिएँ।"},
    {"key": "outside", "icon": "sun", "en": "Step outside", "hi": "बाहर जाएँ",
     "en_desc": "Spend a few minutes outdoors.", "hi_desc": "कुछ मिनट बाहर बिताएँ।"},
    {"key": "connect", "icon": "message-circle", "en": "Contact someone you trust", "hi": "किसी अपने से बात करें",
     "en_desc": "Reach out to a person you feel safe with.", "hi_desc": "किसी भरोसेमंद व्यक्ति से जुड़ें।"},
    {"key": "winddown", "icon": "moon", "en": "Wind-down routine", "hi": "आराम की दिनचर्या",
     "en_desc": "Ease toward rest with a calm routine.", "hi_desc": "शांत दिनचर्या के साथ आराम की ओर बढ़ें।"},
]

CONSENT_KEYS = ["mood_history", "health_data", "sleep_data", "activity_data",
                "heart_data", "personal_insights", "ai_summaries",
                "psychologist_sharing", "analytics", "marketing"]

METRIC_LABELS = {
    "sleep_minutes": {"en": "sleep", "hi": "नींद"},
    "sleep_consistency": {"en": "sleep consistency", "hi": "नींद की नियमितता"},
    "steps": {"en": "steps", "hi": "कदम"},
    "activity_minutes": {"en": "activity", "hi": "गतिविधि"},
    "resting_hr": {"en": "resting heart rate", "hi": "आराम की हृदय गति"},
    "hrv": {"en": "heart rate variability", "hi": "हृदय गति परिवर्तनशीलता"},
}

# A composition × trend matrix that turns the Feel Map (mix of low/steady/bright
# days) and the Mood trend (direction over the window) into a SPECIFIC, non-generic
# reflection for "Read your story". Supportive, non-diagnostic.
STORY_MATRIX = {
    "bright": {
        "improving": "Your recent days have leaned bright, and they've kept lifting. Whatever you've been doing lately seems to be helping — it's worth noticing what's behind it.",
        "declining": "Overall this has been a bright stretch, though the last few days eased off a little. A gentle dip after good days is completely normal — be kind to your energy.",
        "steady": "You've had a steadily bright run. Consistency like this is quietly powerful; small good routines really do add up.",
        "volatile": "There's been plenty of brightness, even if your days swung a fair bit. Ups and downs around good moments are still good news overall.",
    },
    "steady": {
        "improving": "Your days have been fairly even, and lately they've started to lift. Steady ground with a gentle rise is a hopeful shape.",
        "declining": "You've been mostly on even ground, with a slight downward drift recently. Nothing dramatic — just a nudge to rest and check in with yourself.",
        "steady": "Your mood has held steady and level. Flat stretches aren't nothing — they're a stable base you can build small things on.",
        "volatile": "Underneath a mostly even picture, some days swung more than others. Naming those wobble days can help you spot what stirs them.",
    },
    "low": {
        "improving": "It's been a heavier stretch, but the recent trend is quietly lifting. That upward turn matters — hold onto whatever is helping.",
        "declining": "These have been heavier days, and the trend kept dipping. Talking it through with a psychologist on a 15-minute call could help.",
        "steady": "You've sat with a lot of heaviness lately, holding fairly level. That's hard to do — please be gentle; a 15-minute psychologist call could help.",
        "volatile": "Heavier days have come and gone in waves. A 15-minute psychologist call and steadier routines can make a real difference.",
    },
    "mixed": {
        "improving": "Your days have been a real mix, and the overall direction is lifting. Range is human — and the trend is a kind one right now.",
        "declining": "It's been a mixed stretch that edged downward lately. If the dip continues, a 15-minute psychologist call could help.",
        "steady": "You've moved between heavier and brighter days around a steady centre. That variety is part of a full emotional life.",
        "volatile": "Your days swung widely between light and heavy. Big swings can be tiring — noticing your triggers is a strong first step.",
    },
}
