"""Legal content (single source for hosted pages). Mirrors the in-app
frontend/src/legal.ts privacy policy, version 1.0."""

PRIVACY_VERSION = "1.0"

PRIVACY_POLICY = [
    {"h": "TherapiShots Privacy Policy", "b": "Version 1.0  ·  Applicable law: Republic of India (including the Digital Personal Data Protection Act, 2023 and the Information Technology Act, 2000).\n\nThis policy explains what we collect, why, and the control you have. By using TherapiShots you acknowledge you have read and understood it."},
    {"h": "1. Introduction", "b": "TherapiShots is an emotional wellbeing platform operated by TherapiShots Private Limited (\"we\", \"us\", \"our\"). This Privacy Policy describes how we collect, use, store, share, and protect your personal information when you use our mobile application and related services (the \"Platform\"). It applies to all users and is governed by the laws of the Republic of India."},
    {"h": "2. Information We Collect", "b": "Personal information: name, email address (optional), phone number, date of birth, language preference, and profile information you provide.\n\nMood information: mood selections, check-in history, reflection notes, mood context (such as work, sleep, relationships), and wellbeing goals.\n\nHealth information (optional): accessed only if you explicitly connect Apple HealthKit or Android Health Connect — for example sleep duration and consistency, steps, walking distance, activity, exercise, resting heart rate, HRV, and calories (if enabled). We access only the categories you authorize.\n\nDevice information: device type, operating system, app version, crash logs, and performance diagnostics."},
    {"h": "3. Information We Do NOT Collect", "b": "TherapiShots does not: continuously monitor your microphone; continuously monitor your camera; read your text messages; read your email; access your contacts unless you explicitly authorize a feature that requires it; or access your location unless a feature specifically requires it and you grant permission."},
    {"h": "4. Why We Collect Information", "b": "We use your information to: create and manage your account; save your mood history; generate wellbeing insights; display trends; provide psychologist discovery and booking; send reminders (only if you enable them); improve app performance and reliability; and prevent fraud and misuse."},
    {"h": "5. AI Processing", "b": "We may use artificial intelligence to summarize your trends, explain validated patterns, and simplify information for you. AI is NOT used to diagnose conditions, prescribe medication, replace psychologists, or make emergency decisions. AI-generated content is informational only."},
    {"h": "6. Health Data Processing", "b": "Health information is processed only after your explicit authorization through Apple HealthKit or Android Health Connect. Connecting health data is entirely optional, and you may disconnect health integrations at any time via your device settings or the app."},
    {"h": "7. Psychologist Sharing", "b": "By default, nothing is shared with a psychologist. You explicitly choose whether to share specific information — such as mood history, sleep trends, activity trends, notes, or AI summaries — before any consultation. There is no automatic sharing."},
    {"h": "8. How Long We Keep Data", "b": "Account and mood data are retained while your account is active. When you delete your account, your personal data is deleted, except where limited retention is required by law or to resolve disputes. Specific retention periods will be published as they are finalised."},
    {"h": "9. Data Security", "b": "We apply reasonable safeguards including encryption in transit, encryption at rest where appropriate, secure authentication, role-based access controls, security monitoring, and periodic security reviews. No system is perfectly secure, but we work to protect your information."},
    {"h": "10. Who Can Access My Data", "b": "Access is role-based: you can access your own data; authorized support staff may access data only when necessary to help you; and psychologists can access information only when you explicitly choose to share it. Marketing teams never access your mood or health information."},
    {"h": "11. Third-Party Providers", "b": "We rely on trusted service providers across categories such as authentication (e.g. SMS OTP), cloud hosting, payments, AI services, push notifications (if enabled), and crash reporting. Each is used only to deliver the services you request, and providers are bound by appropriate confidentiality and data-protection obligations."},
    {"h": "12. International Transfers", "b": "Some providers may process data outside India. Where this occurs, we limit it to the categories of providers necessary to deliver the service and apply appropriate contractual and technical safeguards consistent with applicable law."},
    {"h": "13. Your Rights", "b": "Subject to applicable law, you may: access your data; correct inaccurate information; export your information; delete your account; withdraw optional consents; disconnect Apple HealthKit / Android Health Connect; change notification preferences; and contact our Grievance Officer. You can delete your account and data anytime from Me → Delete account."},
    {"h": "14. Cookies (Website)", "b": "Our website may use cookies for basic functionality and analytics. This is separate from the app, which does not rely on advertising cookies. Website cookie preferences are managed on the website."},
    {"h": "15. Children's Privacy", "b": "TherapiShots is intended only for individuals aged 18 or older. If we discover that an account belongs to someone under 18, the account may be removed in accordance with applicable law."},
    {"h": "16. Sensitive Personal Data", "b": "We treat your mood information and any connected health information as sensitive personal data and handle it with additional care, given its nature."},
    {"h": "17. Automated Decision-Making", "b": "TherapiShots does not make automated medical or treatment decisions. Pattern insights are intended to support personal reflection and must not be treated as a diagnosis."},
    {"h": "18. Changes to this Policy", "b": "We may update this Policy from time to time. Material changes will be communicated within the app or by other reasonable means, and where required by law we will request renewed consent."},
    {"h": "19. Contact Information", "b": "TherapiShots Private Limited\nRegistered Office: Flat 25, DDA SFS Flats, Sector 9, Pocket 1, Dwarka, New Delhi\nPrivacy & Grievance Officer: Saurabh\nEmail: privacy@therapishots.com\nWe aim to acknowledge privacy requests within a reasonable time and in accordance with applicable law."},
    {"h": "20. Our Privacy Promise", "b": "• Your mood belongs to you.\n• Your health data belongs to you.\n• Health connections are optional.\n• We only collect the data needed to provide the services you choose.\n• We do not sell your personal health or mood information.\n• You decide what, if anything, is shared with a psychologist.\n• You can disconnect health integrations at any time.\n• You can request deletion of your account and personal information, subject to legal obligations.\n• We strive to explain clearly how AI is used within TherapiShots.\n\nThis promise is a plain-language summary and does not replace the full Privacy Policy above."},
]
